Controllers/ClothController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourStore.Data.interfaces;
using YourStore.Data.Models;
using YourStore.ViewModels;

namespace YourStore.Controllers
{
    public class ClothController : Controller
    {

        private readonly IClothRepository _clothRepository;
        private readonly ICategoryRepository _categoryRepository;

        public ClothController(IClothRepository clothRepository, ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
            _clothRepository = clothRepository;
        }

        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Clothes> clothes;

            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                clothes = _clothRepository.Clothes.OrderBy(n => n.ClothesId);
                currentCategory = "All clothes";
            }
            else
            {
                if (string.Equals("Men", _category, StringComparison.OrdinalIgnoreCase))
                {
                    clothes = _clothRepository.Clothes.Where(p => p.Category.CategoryName.Equals("Men")).OrderBy(p => p.Name);
                }
                else
                    clothes = _clothRepository.Clothes.Where(p => p.Category.CategoryName.Equals("Women")).OrderBy(p => p.Name);

                currentCategory = _category;
            }
            return View(new ClothListViewModel
            {
                Clothes = clothes,
                CurrentCategory = currentCategory
            });
        }
        public ViewResult Search(string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Clothes> drinks;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                drinks = _clothRepository.Clothes.OrderBy(p => p.ClothesId);
            }
            else
            {
                drinks = _clothRepository.Clothes.Where(p => p.Name.ToLower().Contains(_searchString.ToLower()));
            }

            return View("~/Views/Cloth/List.cshtml", new ClothListViewModel { Clothes = drinks, CurrentCategory = "All clothes" });
        }

        public ViewResult Details(int clothId)
        {
            var cloth = _clothRepository.Clothes.FirstOrDefault(d => d.ClothesId == clothId);
            if (cloth == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            return View(cloth);
        }
    }
}



 

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace YourStore.Controllers
{
    public class ContactController : Controller
    {
        // GET: /<controller>/
        public ViewResult Index()
        {
            return View();
        }
    }
}

Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using YourStore.Data.interfaces;
using YourStore.Data.Models;
using YourStore.ViewModels;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace YourStore.Controllers
{
    public class ShoppingCartController : Controller
    {


        private readonly IClothRepository _clothRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IClothRepository clothRepository, ShoppingCart shoppingCart)
        {
            _clothRepository = clothRepository;
            _shoppingCart = shoppingCart;
        }

        [Authorize]
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        [Authorize]
        public RedirectToActionResult AddToShoppingCart(int clothid)
        {
            var selectedCloth = _clothRepository.Clothes.FirstOrDefault(p => p.ClothesId == clothid);
            if (selectedCloth != null)
            {
                _shoppingCart.AddToCart(selectedCloth, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int clothId)
        {
            var selectedCloth = _clothRepository.Clothes.FirstOrDefault(p => p.ClothesId == clothId);
            if (selectedCloth != null)
            {
                _shoppingCart.RemoveFromCart(selectedCloth);
            }
            return RedirectToAction("Index");
        }

    }
 }

Views/Shared/Carousel.cshtml
<div class="row carousel-holder marginTop1">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

Views/Shared/ClothOverviewSummary.cshtml
@model Clothes

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Cloth" asp-action="Details" asp-route-id="@Model.ClothesId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart text-right">
            <p class="button ">
                <a class="btn btn-success " id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-pieId="@Model.ClothesId">
                    Add to cart
                </a>
            </p>
        </div>
    </div>
</div>

Views/Shared/ClothesSummary.cshtml
@model Clothes

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Cloth" asp-action="Details" asp-route-clothId="@Model.ClothesId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart text-right">
            <p class="button ">
                <a class="btn btn-success" id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-clothId="@Model.ClothesId">
                    Add to cart
                </a>
            </p>
        </div>
    </div>
</div>

Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" class="navbar-right">
        <ul class="nav navbar-nav navbar-left">
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a id="registerLink" asp-controller="Account" asp-action="Register"> Register </a></li>
        <li><a id="loginLink" asp-controller="Account" asp-action="Login"> Log in </a></li>
    </ul>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <title>YourStore</title>
</head>
<body>
    <nav class="navbar navbar-inverse " role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index"> Home </a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li><a asp-controller="Contact" asp-action="Index">Contact Us</a></li>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
                <ul class="navbar-right">
                    @await Html.PartialAsync("LoginPartial")
                </ul>
                <form class="navbar-form navbar-right" asp-controller="Cloth" asp-action="Search" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search for a cloth" name="searchString" value="@ViewData["searchString"]">
                    </div>
                </form>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container body-content" style="padding:50px;">
        @RenderBody()
        <hr />
        <footer>
            <p><a target="_blank" href="https://github.com/Barti28">&copy; 2019 - Barjam(Barti) Basha</a></p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>