ViewModels/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourStore.Data.Models;

namespace YourStore.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShoppingCart ShoppingCart { get; set; }

        public decimal ShoppingCartTotal { get; set; }

       
    }
}

Controllers/ClothController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourStore.Data.interfaces;
using YourStore.Data.Models;
using YourStore.ViewModels;

namespace YourStore.Controllers
{
    public class ClothController : Controller
    {

        private readonly IClothRepository _clothRepository;
        private readonly ICategoryRepository _categoryRepository;

        public ClothController(IClothRepository clothRepository, ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
            _clothRepository = clothRepository;
        }

        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Clothes> clothes;

            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                clothes = _clothRepository.Clothes.OrderBy(n => n.ClothesId);
                currentCategory = "All clothes";
            }
            else
            {
                if (string.Equals("Men", _category, StringComparison.OrdinalIgnoreCase))
                {
                    clothes = _clothRepository.Clothes.Where(p => p.Category.CategoryName.Equals("Men")).OrderBy(p => p.Name);
                }
                else
                    clothes = _clothRepository.Clothes.Where(p => p.Category.CategoryName.Equals("Women")).OrderBy(p => p.Name);

                currentCategory = _category;
            }
            return View(new ClothListViewModel
            {
                Clothes = clothes,
                CurrentCategory = currentCategory
            });
        }
        public ViewResult Search(string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Clothes> drinks;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                drinks = _clothRepository.Clothes.OrderBy(p => p.ClothesId);
            }
            else
            {
                drinks = _clothRepository.Clothes.Where(p => p.Name.ToLower().Contains(_searchString.ToLower()));
            }

            return View("~/Views/Cloth/List.cshtml", new ClothListViewModel { Clothes = drinks, CurrentCategory = "All clothes" });
        }

        public ViewResult Details(int clothId)
        {
            var cloth = _clothRepository.Clothes.FirstOrDefault(d => d.ClothesId == clothId);
            if (cloth == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            return View(cloth);
        }
    }
}



 

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using YourStore.Data.interfaces;
using YourStore.Data.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace YourStore.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;

        public OrderController(IOrderRepository orderRepository, ShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }

        [Authorize]
        // GET: /<controller>/
        public IActionResult Checkout()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            if (_shoppingCart.ShoppingCartItems.Count ==0)
            {
                ModelState.AddModelError("", "Your card is empty, add some clothes first");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }
            return View(order);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thank you for your order! :)";
            return View();
        }


    }
}

Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using YourStore.Data.interfaces;
using YourStore.Data.Models;
using YourStore.ViewModels;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace YourStore.Controllers
{
    public class ShoppingCartController : Controller
    {


        private readonly IClothRepository _clothRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IClothRepository clothRepository, ShoppingCart shoppingCart)
        {
            _clothRepository = clothRepository;
            _shoppingCart = shoppingCart;
        }

        [Authorize]
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        [Authorize]
        public RedirectToActionResult AddToShoppingCart(int clothid)
        {
            var selectedCloth = _clothRepository.Clothes.FirstOrDefault(p => p.ClothesId == clothid);
            if (selectedCloth != null)
            {
                _shoppingCart.AddToCart(selectedCloth, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int clothId)
        {
            var selectedCloth = _clothRepository.Clothes.FirstOrDefault(p => p.ClothesId == clothId);
            if (selectedCloth != null)
            {
                _shoppingCart.RemoveFromCart(selectedCloth);
            }
            return RedirectToAction("Index");
        }

    }
 }

Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel

<div class="row checkoutForm">
    <h2>Your shopping cart</h2>
    <h4>Here are the clothes in your shopping cart.</h4>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Clothes</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
            {
                <tr>
                    <td class="text-center">@line.Amount</td>
                    <td class="text-left">@line.Clothes.Name</td>
                    <td class="text-right">@line.Clothes.Price.ToString("c")</td>
                    <td class="text-right">
                        @((line.Amount * line.Clothes.Price).ToString("c"))
                    </td>
                    <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-clothId="@line.Clothes.ClothesId"></a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.ShoppingCartTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-right">
        <div class="btn-group ">
            <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
            <a class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Add more clothes<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a asp-controller="Cloth" asp-action="List" asp-route-category="Men">Men</a></li>
                    <li><a asp-controller="Cloth" asp-action="List" asp-route-category="Women">Women </a></li>
                </ul>
            </a>
        </div>
    </div>
</div>